# -*- coding: utf-8 -*-
"""My Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UmB95pOwDs8N_MK32Sr3NyD0Dl98GVKQ

# Importing the important Libraries
"""

import pandas as pd
import numpy as np
from scipy.stats import ttest_1samp
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import svm
from sklearn.preprocessing import StandardScaler

"""#reading the file"""

file_path = "//content/My_project.xlsx"

KADDB_file = pd.read_excel(file_path)

KADDB_file.head()

"""#data preprocessing"""

print(KADDB_file.isnull().sum())

question_cols = ['Q1','Q2','Q3','Q4','Q5','Q6',
                 'Q7','Q8','Q9','Q10','Q11','Q12']

KADDB_file = KADDB_file.iloc[:, 1:]

print(KADDB_file.shape)

questions = [f"Q{i+1}" for i in range(KADDB_file.shape[1]-1)] + ["GPA"]


KADDB_file.columns = questions


print(KADDB_file.head())

print(KADDB_file.columns)

KADDB_file["GPA_Letter"] = KADDB_file["GPA"].map({
    5: "A",
    4: "B",
    3: "C",
    2: "D"
})

KADDB_file.head()

"""#the statistical analysis"""

mean=KADDB_file["Hypothesis_Score"] = KADDB_file[question_cols].mean(axis=1)

mean.head()

KADDB_file["score"] = KADDB_file[question_cols].mean(axis=1)

KADDB_file.head()

t_stat, p_value = ttest_1samp(KADDB_file["score"], 3)

print(t_stat)

print(p_value)

alpha = 0.05

if p_value < alpha:
    print("The mean score is less than 3.")
    print("Reject the null hypothesis. There is a significant difference between the mean score and 3.")
    print("The statistical analysis revealed a highly significant result (p < 0.05). Accordingly, the null hypothesis was rejected, and the alternative hypothesis was strongly supported..")
else:
    print("The mean score is greater than 3.")
    print("Fail to reject the null hypothesis. There is no significant difference between the mean score and 3.")
    print("The statistical analysis revealed a non-significant result (p ≥ 0.05). Accordingly, the null hypothesis was not rejected, and the alternative hypothesis was not supported.")

"""#data visualization

#"This plot represents the mean distribution of student grades. It indicates that there is no significant variance, the data is not random, and it is suitable for a Machine Learning model."
"""

plt.figure()
plt.hist(KADDB_file['score'])
plt.axvline(3)
plt.xlabel('Mean Score')
plt.ylabel('Frequency')
plt.title('Distribution of Students Mean Scores')
plt.show()

"""#adding column for the machine learning"""

risk_map = {
    "A": 0,
    "B": 0,
    "C": 1,
    "D": 1
}

KADDB_file["Risk"] = KADDB_file["GPA_Letter"].map(risk_map)

KADDB_file

"""#verifying the count of data"""

KADDB_file["Risk"].value_counts()

"""#creating the x and y for the train and test"""

X = KADDB_file[[f"Q{i}" for i in range(1,13)]]
y = KADDB_file["Risk"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

"""# Initially, Random Forest and SVM were tested, but both yielded very low accuracy. I then applied Z-score standardization (StandardScaler) to handle the small dataset and normalize feature scales, which significantly improved the model's accuracy."""

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = RandomForestClassifier(random_state=42)
model.fit(X_train_scaled, y_train)

y_predection1 = model.predict(X_test)

print(confusion_matrix(y_test, y_predection1))

print(classification_report(y_test, y_predection1))